/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author k.andrade
 */
public class Interface_update_jogo extends javax.swing.JFrame {

    /**
     * Creates new form Interface_update_jogo
     */
    public Interface_update_jogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jfield_nome_jogo = new javax.swing.JTextField();
        jfield_genero_jogo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jlbl_preco_jogo = new javax.swing.JLabel();
        jfield_preco_jogo = new javax.swing.JTextField();
        jfield_id_jogo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbutton_mudar = new javax.swing.JToggleButton();
        jlbl_id_deletado = new javax.swing.JLabel();
        jfield_id_deletado = new javax.swing.JTextField();
        jbutton_deletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome jogo:");

        jLabel2.setText("Gênero:");

        jlbl_preco_jogo.setText("Preço jogo:");

        jLabel3.setText("ID:");

        jbutton_mudar.setText("Mudar conteúdo");
        jbutton_mudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_mudarActionPerformed(evt);
            }
        });

        jlbl_id_deletado.setText("ID a ser deletado:");

        jfield_id_deletado.setPreferredSize(new java.awt.Dimension(300, 60));
        jfield_id_deletado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_id_deletadoActionPerformed(evt);
            }
        });

        jbutton_deletar.setText("Deletar");
        jbutton_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_deletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfield_preco_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbl_preco_jogo)
                            .addComponent(jfield_genero_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jfield_id_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfield_id_deletado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbl_id_deletado)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfield_nome_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbutton_deletar)
                                .addGap(115, 115, 115))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jbutton_mudar)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbl_id_deletado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfield_id_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfield_id_deletado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfield_nome_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbutton_deletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield_genero_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbl_preco_jogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jfield_preco_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutton_mudar)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton_mudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_mudarActionPerformed
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/jogos";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "UPDATE jogo SET nome_jogo = ?, genero_jogo = ?, preco_jogo = ? where id_jogo = ?";
            
            statement = conexao.prepareStatement(sql);
            
            statement.setString(1, jfield_nome_jogo.getText()); // nome do jogo
            statement.setString(2, jfield_genero_jogo.getText()); // genero do jogo
            statement.setString(3, jfield_preco_jogo.getText()); // preço do jogo
            statement.setString(4, jfield_id_jogo.getText()); // ID

            statement.executeUpdate();
            
            System.out.println("Deu certo");
        } catch (SQLException ex) {
            //Logger.getLogger(Interface_update_jogo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Deu esse erro aqui: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbutton_mudarActionPerformed

    private void jfield_id_deletadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_id_deletadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_id_deletadoActionPerformed

    private void jbutton_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_deletarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/jogos";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection(url, usuario, senha);
            
            String sql = "DELETE FROM jogo where id_jogo = ?";
            
            statement = conexao.prepareStatement(sql);

            statement.setString(1, jfield_id_deletado.getText()); // ID

            statement.executeUpdate();
            
            System.out.println("Deu certo");
        } catch (SQLException ex) {
            //Logger.getLogger(Interface_update_jogo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Deu esse erro aqui: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbutton_deletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_update_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_update_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_update_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_update_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_update_jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbutton_deletar;
    private javax.swing.JToggleButton jbutton_mudar;
    private javax.swing.JTextField jfield_genero_jogo;
    private javax.swing.JTextField jfield_id_deletado;
    private javax.swing.JTextField jfield_id_jogo;
    private javax.swing.JTextField jfield_nome_jogo;
    private javax.swing.JTextField jfield_preco_jogo;
    private javax.swing.JLabel jlbl_id_deletado;
    private javax.swing.JLabel jlbl_preco_jogo;
    // End of variables declaration//GEN-END:variables
}
