/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author k.andrade
 */
public class Interface_cadastro_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Interface_cadastro_cliente
     */
    public Interface_cadastro_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_numero_casa = new javax.swing.JLabel();
        jfield_numero_casa = new javax.swing.JTextField();
        jfield_cep = new javax.swing.JTextField();
        jlbl_cep = new javax.swing.JLabel();
        jfield_servico_contratado = new javax.swing.JTextField();
        jlbl_servico_contratado = new javax.swing.JLabel();
        jfield_telefone = new javax.swing.JTextField();
        jlbl_telefone = new javax.swing.JLabel();
        jlbl_cpf = new javax.swing.JLabel();
        jfield_cpf_cliente = new javax.swing.JTextField();
        jbutton_cadastrar = new javax.swing.JButton();
        jfield_raca_pet = new javax.swing.JTextField();
        jlbl_raca_pet = new javax.swing.JLabel();
        jfield_nome_pet = new javax.swing.JTextField();
        jlbl_pet = new javax.swing.JLabel();
        jfield_cliente = new javax.swing.JTextField();
        jlbl_cliente = new javax.swing.JLabel();
        jfield_rua = new javax.swing.JTextField();
        jlbl_rua = new javax.swing.JLabel();
        jfield_bairro = new javax.swing.JTextField();
        jlbl_bairro = new javax.swing.JLabel();
        jfield_cidade = new javax.swing.JTextField();
        jlbl_cidade = new javax.swing.JLabel();
        jlbl_porte = new javax.swing.JLabel();
        jfield_porte = new javax.swing.JTextField();
        jlbl_cor = new javax.swing.JLabel();
        jfield_cor = new javax.swing.JTextField();
        jlbl_sexo = new javax.swing.JLabel();
        jfield_sexo = new javax.swing.JTextField();
        jlbl_descricao_comportamento = new javax.swing.JLabel();
        jfield_descricao_comportamento = new javax.swing.JTextField();
        jlbl_saude_pet = new javax.swing.JLabel();
        jfield_saude_pet = new javax.swing.JTextField();
        jlbl_complemento = new javax.swing.JLabel();
        jfield_complemento = new javax.swing.JTextField();
        jfield_e_mail = new javax.swing.JTextField();
        jlbl_e_mail = new javax.swing.JLabel();
        jfield_especie = new javax.swing.JTextField();
        jlbl_especie = new javax.swing.JLabel();
        jlbl_alergias = new javax.swing.JLabel();
        jfield_alergia_pet = new javax.swing.JTextField();
        jlbl_requisitos_especiais = new javax.swing.JLabel();
        jfield_requisitos_especiais = new javax.swing.JTextField();
        jlbl_info_alimentacao = new javax.swing.JLabel();
        jfield_info_alimentacao = new javax.swing.JTextField();
        jlbl_info_social = new javax.swing.JLabel();
        jfield_info_social = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbl_numero_casa.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_numero_casa.setText("N°:");

        jfield_numero_casa.setBackground(new java.awt.Color(255, 255, 255));
        jfield_numero_casa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_numero_casaActionPerformed(evt);
            }
        });

        jfield_cep.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cepActionPerformed(evt);
            }
        });

        jlbl_cep.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cep.setText("CEP:");

        jfield_servico_contratado.setBackground(new java.awt.Color(255, 255, 255));
        jfield_servico_contratado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_servico_contratadoActionPerformed(evt);
            }
        });

        jlbl_servico_contratado.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_servico_contratado.setText("Serviço contratado:");

        jfield_telefone.setBackground(new java.awt.Color(255, 255, 255));
        jfield_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_telefoneActionPerformed(evt);
            }
        });

        jlbl_telefone.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_telefone.setText("Telefone:");

        jlbl_cpf.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cpf.setText("CPF:");

        jfield_cpf_cliente.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cpf_cliente.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_cpf_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cpf_clienteActionPerformed(evt);
            }
        });

        jbutton_cadastrar.setBackground(new java.awt.Color(51, 255, 51));
        jbutton_cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jbutton_cadastrar.setText("Cadastrar");
        jbutton_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_cadastrarActionPerformed(evt);
            }
        });

        jfield_raca_pet.setBackground(new java.awt.Color(255, 255, 255));
        jfield_raca_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_raca_petActionPerformed(evt);
            }
        });

        jlbl_raca_pet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_raca_pet.setText("Raça do pet:");

        jfield_nome_pet.setBackground(new java.awt.Color(255, 255, 255));
        jfield_nome_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_nome_petActionPerformed(evt);
            }
        });

        jlbl_pet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_pet.setText("Nome do pet:");

        jfield_cliente.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cliente.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_clienteActionPerformed(evt);
            }
        });

        jlbl_cliente.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cliente.setText("Nome completo do cliente:");

        jfield_rua.setBackground(new java.awt.Color(255, 255, 255));
        jfield_rua.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_ruaActionPerformed(evt);
            }
        });

        jlbl_rua.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_rua.setText("Rua:");

        jfield_bairro.setBackground(new java.awt.Color(255, 255, 255));
        jfield_bairro.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_bairroActionPerformed(evt);
            }
        });

        jlbl_bairro.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_bairro.setText("Bairro:");

        jfield_cidade.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cidade.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_cidadeActionPerformed(evt);
            }
        });

        jlbl_cidade.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cidade.setText("Cidade:");

        jlbl_porte.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_porte.setText("Porte:");

        jfield_porte.setBackground(new java.awt.Color(255, 255, 255));
        jfield_porte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_porteActionPerformed(evt);
            }
        });

        jlbl_cor.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_cor.setText("Cor:");

        jfield_cor.setBackground(new java.awt.Color(255, 255, 255));
        jfield_cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_corActionPerformed(evt);
            }
        });

        jlbl_sexo.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_sexo.setText("Sexo:");

        jfield_sexo.setBackground(new java.awt.Color(255, 255, 255));
        jfield_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_sexoActionPerformed(evt);
            }
        });

        jlbl_descricao_comportamento.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_descricao_comportamento.setText("Descrição do comportamento:");

        jfield_descricao_comportamento.setBackground(new java.awt.Color(255, 255, 255));
        jfield_descricao_comportamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_descricao_comportamentoActionPerformed(evt);
            }
        });

        jlbl_saude_pet.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_saude_pet.setText("Saúde do pet:");

        jfield_saude_pet.setBackground(new java.awt.Color(255, 255, 255));
        jfield_saude_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_saude_petActionPerformed(evt);
            }
        });

        jlbl_complemento.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_complemento.setText("Complemento:");

        jfield_complemento.setBackground(new java.awt.Color(255, 255, 255));
        jfield_complemento.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_complementoActionPerformed(evt);
            }
        });

        jfield_e_mail.setBackground(new java.awt.Color(255, 255, 255));
        jfield_e_mail.setPreferredSize(new java.awt.Dimension(100, 22));
        jfield_e_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_e_mailActionPerformed(evt);
            }
        });

        jlbl_e_mail.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_e_mail.setText("E-mail:");

        jfield_especie.setBackground(new java.awt.Color(255, 255, 255));
        jfield_especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_especieActionPerformed(evt);
            }
        });

        jlbl_especie.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_especie.setText("Espécie:");

        jlbl_alergias.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_alergias.setText("Alergias (se houver):");

        jfield_alergia_pet.setBackground(new java.awt.Color(255, 255, 255));
        jfield_alergia_pet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_alergia_petActionPerformed(evt);
            }
        });

        jlbl_requisitos_especiais.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_requisitos_especiais.setText("Requisitos especiais (dietas, medicações):");

        jfield_requisitos_especiais.setBackground(new java.awt.Color(255, 255, 255));
        jfield_requisitos_especiais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_requisitos_especiaisActionPerformed(evt);
            }
        });

        jlbl_info_alimentacao.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_info_alimentacao.setText("Informações sobre alimentação:");

        jfield_info_alimentacao.setBackground(new java.awt.Color(255, 255, 255));
        jfield_info_alimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_info_alimentacaoActionPerformed(evt);
            }
        });

        jlbl_info_social.setForeground(new java.awt.Color(0, 0, 0));
        jlbl_info_social.setText("Interações socias (como se dá com outros pets):");

        jfield_info_social.setBackground(new java.awt.Color(255, 255, 255));
        jfield_info_social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfield_info_socialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_servico_contratado)
                            .addComponent(jfield_servico_contratado, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jfield_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_cep)
                                .addGap(176, 176, 176)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_numero_casa)
                            .addComponent(jfield_numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbl_cliente)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbl_cpf)
                                .addComponent(jfield_cpf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbl_telefone)
                                .addComponent(jfield_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jfield_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbl_complemento)
                    .addComponent(jfield_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_rua)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbl_bairro)
                                .addComponent(jfield_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlbl_cidade)
                                .addComponent(jfield_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jfield_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbl_e_mail)
                    .addComponent(jfield_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlbl_descricao_comportamento)
                        .addComponent(jlbl_saude_pet)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlbl_cor)
                            .addGap(296, 296, 296)
                            .addComponent(jlbl_sexo))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jfield_cor)
                                .addComponent(jlbl_pet, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jfield_nome_pet)
                                .addComponent(jlbl_raca_pet, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jfield_raca_pet, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbl_especie)
                                        .addComponent(jfield_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlbl_porte)
                                        .addComponent(jfield_porte, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jfield_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jfield_descricao_comportamento)
                        .addComponent(jfield_saude_pet))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_alergias)
                            .addComponent(jfield_alergia_pet, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_requisitos_especiais)
                            .addComponent(jfield_requisitos_especiais, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_info_alimentacao)
                            .addComponent(jfield_info_alimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_info_social)
                            .addComponent(jfield_info_social, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 314, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(604, 604, 604)
                .addComponent(jbutton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfield_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_cpf)
                            .addComponent(jlbl_telefone))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfield_cpf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfield_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_e_mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfield_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_cep)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbl_servico_contratado)
                                    .addComponent(jlbl_numero_casa))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jfield_servico_contratado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfield_numero_casa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_rua)
                        .addGap(6, 6, 6)
                        .addComponent(jfield_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_bairro)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_cidade)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbl_complemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfield_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_pet)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_nome_pet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_especie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfield_especie, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_raca_pet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfield_raca_pet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_porte)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_porte, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbl_cor)
                            .addComponent(jlbl_sexo))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jfield_cor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfield_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_descricao_comportamento)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_descricao_comportamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbl_saude_pet)
                                        .addGap(6, 6, 6)
                                        .addComponent(jfield_saude_pet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlbl_alergias)
                                        .addGap(6, 6, 6)
                                        .addComponent(jfield_alergia_pet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbl_requisitos_especiais)
                                        .addGap(6, 6, 6)
                                        .addComponent(jfield_requisitos_especiais, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbl_info_alimentacao)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_info_alimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbl_info_social)
                                .addGap(6, 6, 6)
                                .addComponent(jfield_info_social, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jbutton_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfield_numero_casaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_numero_casaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_numero_casaActionPerformed

    private void jfield_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cepActionPerformed

    private void jfield_servico_contratadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_servico_contratadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_servico_contratadoActionPerformed

    private void jfield_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_telefoneActionPerformed

    private void jfield_cpf_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cpf_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cpf_clienteActionPerformed

    private void jbutton_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_cadastrarActionPerformed
        // TODO add your handling code here:
        Connection conexao = null;
        PreparedStatement statement = null;

        String url = "jdbc:mysql://localhost:3306/cadastro_pets";
        String usuario = "root";
        String senha = "";

        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
            String sql = "INSERT INTO cliente (nome_cliente, cpf_cliente, telefone, e_mail, servico_contratado, nome_pet, raca_pet) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            statement = conexao.prepareStatement(sql);
            //statement.setString(1, jfield_cliente.getText()); // nome cliente
            //statement.setString(2, jfield_nome_pet.getText()); // nome pet
            
            /*statement.setString(3, .getText()); // cpf cliente
            statement.setString(4, .getText()); // raca pet
            statement.setString(5, .getText()); // raca pet
            statement.setString(6, .getText()); // raca pet
            statement.setString(7, .getText()); // raca pet
            statement.setString(8, .getText()); // raca pet
            statement.setString(9, .getText()); // raca pet
            statement.setString(10, .getText()); // raca pet
            statement.setString(11, .getText()); // raca pet
            statement.setString(12, .getText()); // raca pet
            statement.setString(13, .getText()); // raca pet
            statement.setString(14, .getText()); // raca pet
            statement.setString(15, .getText()); // raca pet
            statement.setString(16, .getText()); // raca pet
            statement.setString(17, .getText()); // raca pet
            statement.setString(18, .getText()); // raca pet
            statement.setString(19, .getText()); // raca pet
            statement.setString(20, .getText()); // raca pet
            statement.setString(21, .getText()); // raca pet
            statement.setString(21, .getText()); // raca pet
            statement.setString(22, .getText()); // raca pet
            */
            
            
            statement.executeUpdate();
            System.out.println("Deu certo aqui.");
        } catch (SQLException ex) {
            //Logger.getLogger(Interface_cadastro_cliente.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Deu esse erro aqui ô: " + ex.getMessage());
        }
    }//GEN-LAST:event_jbutton_cadastrarActionPerformed

    private void jfield_raca_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_raca_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_raca_petActionPerformed

    private void jfield_nome_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_nome_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_nome_petActionPerformed

    private void jfield_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_clienteActionPerformed

    private void jfield_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_ruaActionPerformed

    private void jfield_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_bairroActionPerformed

    private void jfield_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_cidadeActionPerformed

    private void jfield_porteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_porteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_porteActionPerformed

    private void jfield_corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_corActionPerformed

    private void jfield_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_sexoActionPerformed

    private void jfield_descricao_comportamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_descricao_comportamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_descricao_comportamentoActionPerformed

    private void jfield_saude_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_saude_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_saude_petActionPerformed

    private void jfield_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_complementoActionPerformed

    private void jfield_e_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_e_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_e_mailActionPerformed

    private void jfield_especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_especieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_especieActionPerformed

    private void jfield_alergia_petActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_alergia_petActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_alergia_petActionPerformed

    private void jfield_requisitos_especiaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_requisitos_especiaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_requisitos_especiaisActionPerformed

    private void jfield_info_alimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_info_alimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_info_alimentacaoActionPerformed

    private void jfield_info_socialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfield_info_socialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfield_info_socialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_cadastro_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_cadastro_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutton_cadastrar;
    private javax.swing.JTextField jfield_alergia_pet;
    private javax.swing.JTextField jfield_bairro;
    private javax.swing.JTextField jfield_cep;
    private javax.swing.JTextField jfield_cidade;
    private javax.swing.JTextField jfield_cliente;
    private javax.swing.JTextField jfield_complemento;
    private javax.swing.JTextField jfield_cor;
    private javax.swing.JTextField jfield_cpf_cliente;
    private javax.swing.JTextField jfield_descricao_comportamento;
    private javax.swing.JTextField jfield_e_mail;
    private javax.swing.JTextField jfield_especie;
    private javax.swing.JTextField jfield_info_alimentacao;
    private javax.swing.JTextField jfield_info_social;
    private javax.swing.JTextField jfield_nome_pet;
    private javax.swing.JTextField jfield_numero_casa;
    private javax.swing.JTextField jfield_porte;
    private javax.swing.JTextField jfield_raca_pet;
    private javax.swing.JTextField jfield_requisitos_especiais;
    private javax.swing.JTextField jfield_rua;
    private javax.swing.JTextField jfield_saude_pet;
    private javax.swing.JTextField jfield_servico_contratado;
    private javax.swing.JTextField jfield_sexo;
    private javax.swing.JTextField jfield_telefone;
    private javax.swing.JLabel jlbl_alergias;
    private javax.swing.JLabel jlbl_bairro;
    private javax.swing.JLabel jlbl_cep;
    private javax.swing.JLabel jlbl_cidade;
    private javax.swing.JLabel jlbl_cliente;
    private javax.swing.JLabel jlbl_complemento;
    private javax.swing.JLabel jlbl_cor;
    private javax.swing.JLabel jlbl_cpf;
    private javax.swing.JLabel jlbl_descricao_comportamento;
    private javax.swing.JLabel jlbl_e_mail;
    private javax.swing.JLabel jlbl_especie;
    private javax.swing.JLabel jlbl_info_alimentacao;
    private javax.swing.JLabel jlbl_info_social;
    private javax.swing.JLabel jlbl_numero_casa;
    private javax.swing.JLabel jlbl_pet;
    private javax.swing.JLabel jlbl_porte;
    private javax.swing.JLabel jlbl_raca_pet;
    private javax.swing.JLabel jlbl_requisitos_especiais;
    private javax.swing.JLabel jlbl_rua;
    private javax.swing.JLabel jlbl_saude_pet;
    private javax.swing.JLabel jlbl_servico_contratado;
    private javax.swing.JLabel jlbl_sexo;
    private javax.swing.JLabel jlbl_telefone;
    // End of variables declaration//GEN-END:variables
}
