/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author k.andrade
 */
public class Interface_teste_conexao extends javax.swing.JFrame {

    /**
     * Creates new form Interface_teste_conexao
     */
    public Interface_teste_conexao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbl_mago_dos_games = new javax.swing.JLabel();
        jlbl_conectado = new javax.swing.JLabel();
        jlbl_ocultar = new javax.swing.JLabel();
        jbutton_exibir = new javax.swing.JButton();
        jbutton_ocultar = new javax.swing.JButton();
        jbutton_mostrar_itens = new javax.swing.JButton();
        jbutton_mostar_rc = new javax.swing.JButton();
        jcombobox_itens = new javax.swing.JComboBox<>();
        jcheckbox_jogar1 = new javax.swing.JCheckBox();
        jradiobutton_jogar2 = new javax.swing.JRadioButton();
        jlbl_itens = new javax.swing.JLabel();
        jlbl_checkbox = new javax.swing.JLabel();
        jlbl_radiobutton = new javax.swing.JLabel();
        jfield_busca = new javax.swing.JTextField();
        jlbl_id = new javax.swing.JLabel();
        jbutton_buscar = new javax.swing.JButton();
        jlbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbl_mago_dos_games.setText("Mago dos Games");
        getContentPane().add(jlbl_mago_dos_games, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jlbl_conectado.setText("conectado");
        getContentPane().add(jlbl_conectado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jlbl_ocultar.setText("não conectado");
        getContentPane().add(jlbl_ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jbutton_exibir.setText("exibir");
        jbutton_exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_exibirActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jbutton_ocultar.setText("ocultar");
        jbutton_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_ocultarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jbutton_mostrar_itens.setText("Mostrar Itens");
        jbutton_mostrar_itens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_mostrar_itensActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_mostrar_itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 142, -1, -1));

        jbutton_mostar_rc.setText("Bora jogar?");
        jbutton_mostar_rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_mostar_rcActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_mostar_rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 142, -1, -1));

        jcombobox_itens.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "The Witcher 3: Wild Hunt", "Portal", "Portal 2", "GTA V", " " }));
        getContentPane().add(jcombobox_itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 229, -1, -1));

        jcheckbox_jogar1.setText("Jogar?");
        jcheckbox_jogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcheckbox_jogar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jcheckbox_jogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 193, -1, -1));

        jradiobutton_jogar2.setText("Jogar 2?");
        jradiobutton_jogar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradiobutton_jogar2ActionPerformed(evt);
            }
        });
        getContentPane().add(jradiobutton_jogar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 193, -1, -1));
        getContentPane().add(jlbl_itens, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 23, -1, -1));
        getContentPane().add(jlbl_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));
        getContentPane().add(jlbl_radiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));
        getContentPane().add(jfield_busca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 150, 40));

        jlbl_id.setText("ID:");
        getContentPane().add(jlbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jbutton_buscar.setText("Buscar");
        jbutton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbutton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jlbl_resultado.setText("jLabel1");
        getContentPane().add(jlbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        setBounds(0, 0, 1144, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jlbl_conectado.setVisible(false);
        jlbl_mago_dos_games.setVisible(false);
        jlbl_ocultar.setVisible(false);
        jbutton_ocultar.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jbutton_exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_exibirActionPerformed
        // TODO add your handling code here:
        jlbl_conectado.setVisible(true);
        jlbl_mago_dos_games.setVisible(false);
        jlbl_ocultar.setVisible(false);
        jbutton_ocultar.setVisible(true);
    }//GEN-LAST:event_jbutton_exibirActionPerformed

    private void jbutton_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_ocultarActionPerformed
        // TODO add your handling code here:
        jlbl_conectado.setVisible(false);
        jlbl_mago_dos_games.setVisible(true);
        jlbl_ocultar.setVisible(true);

    }//GEN-LAST:event_jbutton_ocultarActionPerformed

    private void jcheckbox_jogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcheckbox_jogar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcheckbox_jogar1ActionPerformed

    private void jradiobutton_jogar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradiobutton_jogar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradiobutton_jogar2ActionPerformed

    private void jbutton_mostrar_itensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_mostrar_itensActionPerformed
        // TODO add your handling code here:
        String selecionado = (String) jcombobox_itens.getSelectedItem();
        
        jlbl_itens.setText("Você selecionou o jogo: " + selecionado);
    }//GEN-LAST:event_jbutton_mostrar_itensActionPerformed

    private void jbutton_mostar_rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_mostar_rcActionPerformed
        // TODO add your handling code here:
        boolean checkbox_selecionado = (boolean) jcheckbox_jogar1.isSelected();
        jlbl_checkbox.setText("Check box bora jogar: " + checkbox_selecionado);
        
        boolean radiobutton_selecionado = (boolean) jradiobutton_jogar2.isSelected();
        jlbl_radiobutton.setText("Radio button bora jogar: " + radiobutton_selecionado);
    }//GEN-LAST:event_jbutton_mostar_rcActionPerformed

    private void jbutton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton_buscarActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
        
            String url = "jdbc:mysql://localhost:3306/jogos";
            String usuario = "root";
            String senha = "";
        
            conexao = DriverManager.getConnection(url, usuario, senha);
            String sql = "SELECT nome_jogo FROM jogo WHERE id_jogo = ?";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, jfield_busca.getText()); // ID
            
            ResultSet resultSet = statement.executeQuery(); //Executa a consulta
            
            if (resultSet.next()) {
                String nome_jogo = resultSet.getString("nome_jogo");
                jlbl_resultado.setText(nome_jogo); // Exibe o resultado na JLabel
            }
            else {
                jlbl_resultado.setText("Jogo não encontrado.");
            }
            
            resultSet.close();
            statement.close();
            conexao.close();
        }
        catch (SQLException e) {
            System.out.println("Deu esse erro aqui ô: " + e.getMessage());
        }
    }//GEN-LAST:event_jbutton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_teste_conexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_teste_conexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_teste_conexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_teste_conexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_teste_conexao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutton_buscar;
    private javax.swing.JButton jbutton_exibir;
    private javax.swing.JButton jbutton_mostar_rc;
    private javax.swing.JButton jbutton_mostrar_itens;
    private javax.swing.JButton jbutton_ocultar;
    private javax.swing.JCheckBox jcheckbox_jogar1;
    private javax.swing.JComboBox<String> jcombobox_itens;
    private javax.swing.JTextField jfield_busca;
    private javax.swing.JLabel jlbl_checkbox;
    private javax.swing.JLabel jlbl_conectado;
    private javax.swing.JLabel jlbl_id;
    private javax.swing.JLabel jlbl_itens;
    private javax.swing.JLabel jlbl_mago_dos_games;
    private javax.swing.JLabel jlbl_ocultar;
    private javax.swing.JLabel jlbl_radiobutton;
    private javax.swing.JLabel jlbl_resultado;
    private javax.swing.JRadioButton jradiobutton_jogar2;
    // End of variables declaration//GEN-END:variables
}
